version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend-node

  backend-node:
    build: ./backend-node
    ports:
      - "5000:5000"
    depends_on:
      - backend-python

  backend-python:
    build: ./backend-python
    ports:
      - "8000:8000"
